version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_floreria
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: floreria_digital
    volumes:
      - mysql-data:/var/lib/mysql

  api_tienda:
    build: ./api_tienda
    container_name: api_floreria
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=floreria_digital
      - PORT=3000
    depends_on:
      - mysql

  cliente_tienda:
    build: ./cliente_tienda
    container_name: cliente_floreria
    ports:
      - "8080:80"
    depends_on:
      - api_tienda

volumes:
  mysql-data:
